services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: education
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .

    environment:
      PORT: 4000
      NODE_ENV: development
      DB_HOST: postgres
      DB_NAME: education
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_PORT: 5432
      DB_DIALECT: postgres
      JWT_SECRET: change_me_super_secret
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["4000:4000"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports: ["5173:80"]

volumes:
  postgres_data:
